name: Tests

on:
  push:
    branches: [ master, rc/*, feat/* ]
  pull_request:
    branches: [ master, rc/*, feat/* ]

jobs:
  test:
    name: Unit
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.20.7
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.7
        id: go

      - name: Check out code
        uses: actions/checkout@v3

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
      - name: Unit tests
        run: make test
